numeros = [1, 2, 3]
letras = ["a", "b", "c"]
palabras = ["chanchito", "feliz"]
palabrasFelices = ["chanchito", "feliz", "felipe", "alumnos"]
booleans = [True, False, True, False]
matriz = [[0, 1], [1, 0]]
ceros = [0]*10
alfanumericos = numeros + letras
rango = list(range(1, 11))
chars = list("hola mundo")
